#+TITLE: Notes Towards Annals of the University of Virginia Libraries
#+AUTHOR: James P. Ascher
#+EMAIL: jpa4q@virginia.edu
#+BIBLIOGRAPHY: sources.bib
#+TODO: TODO WAIT | DONE
#+OPTIONS: TOC:nil

* Plan
** Project Title
   Annals of the University of Virginia Libraries
** Goal
   To chart the investigation into truth formed by the day-to-day
   decisions in the Libraries.
** Methods
   - Chronology with citations for events (major and distinctive)
   - identify themes and topics
   - focus on the unit of the year
** Design
   One page per year with a number of sub-sections into meaningful
   divisions of events, e.g. something like hiring, space, books,
   public events, etc. these need to emerge from the materials after
   freer tagging
** Note design
   Divided by decade and then year, each note has a "topic" :tags:
   longer annotations (if needed), a citation and an exact (date)
** Files
   This one and my general bibliography file
** Procedure
   Read Clemons first and then reports and look for patterns
* To Investigate
** TODO Clemons cite:clemons54:library
** TODO /Alumni Bulletin of the University of Virginia/ 1894-
** TODO /Bulletin of the University of Virginia Library/ 1913-23
* Themes
** Enlightenment library
   it seems that the faculty librarian, central position of the
   library and limited access for students suggests an
   Enlightenment-style library; open stacks is an interesting moment,
   then, for the libraries
** Jefferson as duplicating his teacher's libraries
   [[cite:clemons54:library][, p. 7]] suggests this; or that his
   purchasing habits made him a good builder of libraries 8-9
** Can a librarian-bibliographer select, or should faculty?
   1856 appointment of bibliographer, dropped a year later because of
   faculty response
** Does limited access create more circulation?
   Clemons 14
** Professional librarian, or local?
   1857- vote to separate position by BoV; Brockenbrough demonstrated
   that the student was a bad choice; literary studies could be part,
   or not; 1859- communicating with Faculty
** Recording history, social justice, duty to the future
   see 1861: George Frederick Holmes
* Visions
** Librarian as guide to good books [[cite:clemons54:library][, p. x]]
   Jefferson thought of this, Enlightenment tradition
** Enlightenment project [[cite:clemons54:library][, p. xiv]]
   "a living organism dedicated to the enlightenment of free human
   beings.  He would find the Alderman Library, as thousands of
   students and hundreds of scholars have found it, a free and happy
   place.  In it the riches of human knowledge are not jealously
   guarded by suspicious custodians, but they are gladly made available
   to all who seek truth and wisdom, and at every official desk there
   are helping hands."
** Byrd donation of 1899 suggests research collections
