#+TITLE: Notes Towards Annals of the University of Virginia Libraries
#+AUTHOR: James P. Ascher
#+EMAIL: jpa4q@virginia.edu
#+BIBLIOGRAPHY: sources.bib
#+TODO: TODO WAIT | DONE
#+OPTIONS: TOC:nil

* Plan
** Project Title
   Annals of the University of Virginia Libraries
** Goal
   To chart the investigation into truth formed by the day-to-day
   decisions in the Libraries.
** Methods
   - Chronology with citations for events (major and distinctive)
   - identify themes and topics
   - focus on the unit of the year
** Design
   One page per year with a number of sub-sections into meaningful
   divisions of events, e.g. something like hiring, space, books,
   public events, etc. these need to emerge from the materials after
   freer tagging
** Note design
   Divided by decade and then year, each note has a "topic" :tags:
   longer annotations (if needed), a citation and an exact (date)
** Files
   This one and my general bibliography file
** Procedure
   Read Clemons first and then reports and look for patterns
* To Investigate
** TODO Clemons cite:clemons54:library
** TODO /Alumni Bulletin of the University of Virginia/ 1894-
** TODO /Bulletin of the University of Virginia Library/ 1913-23
* Themes
** Enlightenment library
   it seems that the faculty librarian, central position of the
   library and limited access for students suggests an
   Enlightenment-style library; open stacks is an interesting moment,
   then, for the libraries
** Jefferson as duplicating his teacher's libraries
   [[cite:clemons54:library][, p. 7]] suggests this; or that his
   purchasing habits made him a good builder of libraries 8-9
** Can a librarian-bibliographer select, or should faculty?
   1856 appointment of bibliographer, dropped a year later because of
   faculty response
** Does limited access create more circulation?
   Clemons 14
** Professional librarian, or local?
   1857- vote to separate position by BoV; Brockenbrough demonstrated
   that the student was a bad choice; literary studies could be part,
   or not; 1859- communicating with Faculty
** Recording history, social justice, duty to the future
   see 1861: George Frederick Holmes
** Clemons records the history of each staff member [[cite:clemons54:library][, p. 185]]b
* Visions
** Librarian as guide to good books [[cite:clemons54:library][, p. x]]
   Jefferson thought of this, Enlightenment tradition
** Enlightenment project [[cite:clemons54:library][, p. xiv]]
   "a living organism dedicated to the enlightenment of free human
   beings.  He would find the Alderman Library, as thousands of
   students and hundreds of scholars have found it, a free and happy
   place.  In it the riches of human knowledge are not jealously
   guarded by suspicious custodians, but they are gladly made available
   to all who seek truth and wisdom, and at every official desk there
   are helping hands."
** Byrd donation of 1899 suggests research collections
** State legislature is confused as to what "research" might meant [[cite:clemons54:library][, p. 157]]
   saw science research as federal, social and humanities as... ???
   "There is a saying attributed to President Alderman, that liberty is
   not an heritage but a fresh conquest for each generation"
** Library as storehouse of "associations of affection and gratitude" [[cite:clemons54:library][, p. 159]]
   ghosts with Garnett, general books may be anonymous, special
   attributed; after the fact attribution of gifts
* More sources
** First borrowing rules
   Hello all,
 
While doing some research in the University of Virginia Board of Visitors minutes, I read this passage and saw the genesis of some of our policies (indefinite loan of books to faculty; books provided for reading, not for use as textbooks)  Enjoyed it, so passing it along.  –Melissa
p.s. And be vigilant in your watch for “derangement of the books.”
 
Special meeting of the Board, held at the University March 4, 1825:
 
For the use and care of the library the board now establishes the following regulations.
The Professors of the University shall at all times have free use of the books of the library, in confidence that they will not keep them out longer than while in actual and active use, and leaving with the Librarian a note of the books borrowed.
Books may be lent to the Students of the university, by the Librarian, and by no other person, on a written Permit from a Professor whom such Student attends, specifying the day beyond which they shall not be retained. but it is meant that the books lent are for reading only, and not for the ordinary purpose of getting lessons in them as schoolbooks.
No Student shall carry any book borrowed from the Library, out of the precincts of the University ; nor shall any Student be permitted to have more than three volumes in his possession at any time.
If a Student shall not return a borrowed book on or before the day limited in his Permit, he shall recieve no other until it be returned; and he shall pay moreover for every week's detention, beyond the limitation, 10. cents for a 12mo. or book of smaller size, 20. cents for an 8vo. 30. cents for a 4to. and 40. cents for a folio.
Not every book in the Library shall be free to be lent to Students, but such only as shall not be expressly prohibited by the Faculty on account of their rarity, value or liableness to injury.
No Student shall ever be in the Library but in presence of the Librarian, or of some Professor whom he attends, nor shall be allowed to take any book from the shelves, nor remain in the room to read or consult any book, but during such presence.
If any Student deface, injure, or lose any book of the library, he shall pay the value of the book if defaced, double value if injured, and threefold, if lost; and shall be suspended from the privilege of borrowing during such term as the Faculty shall adjudge.
On some one day of every week, during term, and during one hour of that day, (such day and hour to be fixed on by the Faculty) the Librarian shall attend in the Library, to recieve books returned, and to lend such others as shall be applied fort according to rule. and at some one hour of every day (to be also fixed by the Faculty) the Librarian shall attend, if requested by any Professor, to lend to such Professor such book or books as he may require, & to recieve any he may have to return.
The Librarian shall make an entry of every book lent, and cancel the same when returned, so that it may always be known in what hands every book is.
Strangers whom the Librarian may be willing to attend, may visit the library; but, to prevent derangement of the books, they are to take no book from the shelf, but in his presence. they may also be permitted to consult any book, to read in it, make notes or quotations from it, at the table, under such accomodations and arrangements as the Librarian shall prescribe, on his own responsibility.
Resolved that the salary of the Librarian be raised to the sum of 150. Dollars.
** Reports of librarian
   http://search.lib.virginia.edu/catalog/u4039501

 or possibly here:

http://search.lib.virginia.edu/catalog/u3888708
** More reports
    http://search.lib.virginia.edu/catalog/u730190
